name: Check Pull Request

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout 💾
        uses: actions/checkout@v2
        with:
          node-version: '15.x'
          check-katest: true

      - name: Install dependencies 🔧
        run: npm install

      - name: Lint Typescript 🌀
        run: npm run lint-tsx

      - name: Lint Scss 🦑
        run: npm run lint-scss

      - name: Run Tests 🧪
        run: CI=true npm test

      - name: Build 🧬
        run: npm run build
